apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/kafka/logs"]
          volumeMounts:
            - name: kafka-data
              mountPath: /var/kafka/logs
      containers:
        - name: kafka
          image: apache/kafka:4.2.0
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 9094
          envFrom:
            - configMapRef:
                name: kafka-config
          livenessProbe:
            exec:
              command: ["sh", "-c", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
          volumeMounts:
            - name: kafka-data
              mountPath: /var/kafka/logs
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
          




