apiVersion: v1
kind: ConfigMap
metadata:
  name: url-parser-config
data:
  LOG_LEVEL: debug
  # Kafka 
  KAFKA_BROKER: kafka-0.kafka-service:9092
  KAFKA_URL_TOPIC: url
  KAFKA_DLQ_TOPIC: crawler-dlq
  KAFKA_PARSER_TOPIC: parser
  KAFKA_GROUP_ID: parser
  # AWS
  AWS_PROFILE: terraform
  BUCKET_NAME: my-web-crawler-data-dev
  HTML_BUCKET_PREFIX: raw-html
  TEXT_BUCKET_PREFIX: parsed-text
  # DB
  DB_NAME: web-crawler
  DB_COLLECTION: url