services:
  go-url-producer:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile
    container_name: go-url-producer
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      .env.docker
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: url
    restart: on-failure