services:
  url-crawler:
    build:
      context: ../../.. 
      dockerfile: services/crawler/docker/Dockerfile
    container_name: url-crawler
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    env_file:
      .env.docker
    restart: on-failure
