name: Lint

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [initialiser, crawler, parser]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'services/${{ matrix.service }}/go.mod'
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --timeout 5m
          working-directory: services/${{ matrix.service }}

  lint-shared:
    name: Lint shared
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'shared/go.mod'
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --timeout 5m
          working-directory: shared